### ISSUE TITLE
Does not support cron range (',','-')

### ISSUE THREAD

**Issue by UnbounDev** [harrisiirak/cron-parser#102]
The package doesn't seem to support cron statement w/ range syntax, such as ` "00 00 * * * 6-7"` or ` "00 00 * * * 6,7"`, is this a bug or feature request?

Behavior noticed using the following...

Version: `2.4.1`

Environment:
```
Local time: Sun 2017-07-02 13:59:22 PDT
Universal time: Sun 2017-07-02 20:59:22 UTC
RTC time: Sun 2017-07-02 20:59:22
Time zone: America/Los_Angeles (PDT, -0700)
```

Repro:

```
// expected
00 00 * * * 6-7 2017-07-02T14:00:00-07:00
00 00 * * * 7 2017-07-02T14:00:00-07:00
00 00 * * * 6,7 2017-07-02T14:00:00-07:00

// actual
00 00 * * * 6-7 2017-07-08T00:00:00-07:00
00 00 * * * 7 2017-07-02T14:00:00-07:00
00 00 * * * 6,7 2017-07-08T00:00:00-07:00
```

Script (using moment-timezone for clarity):

```js
const cronParser = require("cron-parser");
const moment = require("moment-timezone");

let timezone = "America/Los_Angeles"
let patterns = [
  "00 00 * * * 6-7",
  "00 00 * * * 7",
  "00 00 * * * 6,7",
];
let args = { 
  iterator: true,
  currentDate: '2017-07-02T13:25:00-07:00',
  tz: timezone,
};

patterns.forEach((pattern) => {
  let iterator = cronParser.parseExpression(pattern, args);
  let next = moment(iterator.next().value.toISOString()).tz(timezone).format();
  console.log(pattern, next);
});
```

**Comment by santigimeno** [comment]
I can confirm this bug. Working on a solution

**Comment by santigimeno** [comment]
I've been looking into this and couldn't find an easy solution.

The issue is that internally the `dayOfWeek` field is sorted so always `6` ends up before `7` so a match with `6` is searched in the first place. A solution is converting the `7` to `0` and in fact it solves the issue, but it opens some other issues when `dayOfWeek` is set to a wildcard (`*`) as this is translated into a `0-7` range and then to `[0, 1, 2, 3, 4, 5, 6, 7]` which, if we apply the proposed fix, it would end as `[0, 1, 2, 3, 4, 5, 6]` which won't be considered as a wildcard later on in the `_findSchedule()` function.

I think the issue could be solved altogether if every `field` instead of being an array could be an object like this. For example
```
{
    dayOfWeek: {
      isWildcard: boolean,
      match: array
    }
}
```

This would also solve other cases like when `dayOfWeek` is set to `0-7`. At this moment the parser considers this a `wildcard` which I would argue it's not.

Thoughts? /cc @harrisiirak

**Comment by harrisiirak** [comment]
@santigimeno thanks for looking into this so quickly! You're indeed correct about the direct replacing of the value. That will cause issues. Let me think about it a bit more.

**Comment by BuZZy1337** [comment]
Any solution in sight for this issue?

**Comment by harrisiirak** [comment]
@BuZzy1337 haven't really had time to look into this. It's still top priority tho. Trying to look into this as soon as possible. Thank you reminding this!

**Comment by harrisiirak** [comment]
@FChristian can confirm the issue. Created #123 for this.
