### ISSUE TITLE
Invalid validation state for month range

### ISSUE THREAD

**Issue by harrisiirak** [harrisiirak/cron-parser#123]
Created from: https://github.com/harrisiirak/cron-parser/issues/102#issuecomment-389278004

> Found another strange behaviour which I couldn't explain with the above:
CRON setting 13 23 * 5-7 * works
CRON setting 14 23 * 4-10 * does not work

Results:

> Invalid explicit day of month definition

**Comment by fishcharlie** [comment]
I can not reproduce this issue.

Running the latest version (2.6.0) of this package and Node.js version 10.8.0.

Using the following code.

```
const parser = require('cron-parser');
const result = parser.parseExpression("14 23 * 4-10 *");

console.log(result.next().toDate());
console.log(result.next().toDate());
console.log(result.next().toDate());
```

Produces an output of the following.

```
2019-04-02T05:14:00.000Z
2019-04-03T05:14:00.000Z
2019-04-04T05:14:00.000Z
```

I'd love to help see if I can fix this and submit a PR to help fix it. Can you please provide more information so that I can try to help fix it? @FChristian
