### ISSUE TITLE
with the parseExpression, How do i tell 0 or 7 is Sun ?

### ISSUE THREAD

**Issue by 1401341324** [harrisiirak/cron-parser#255]

**Comment by mohsinamjad** [comment]
In the docs it's written 0 is sunday but in actual it's giving saturday ?
are the docs not updated or is that an issue ?

**Comment by mohsinamjad** [comment]
+1

**Comment by harrisiirak** [comment]
> In the docs it's written 0 is sunday but in actual it's giving saturday ? are the docs not updated or is that an issue ?

Can you elaborate a bit more or an example that will not yield an expected result? As [supported format](https://github.com/harrisiirak/cron-parser#supported-format) section states:

>  day of week (0 - 7, 1L - 7L) (0 or 7 is Sun)

Both, 0 and 7 are valid identifiers for Sunday.

**Comment by mohsinamjad** [comment]
@harrisiirak so it was related to UTC option, when I passed UTC:true it started working fine but if I don't pass that param it subtracts one day maybe it's because of timezone. 
I guess it should be mentioned in docs.

**Comment by harrisiirak** [comment]
> @harrisiirak so it was related to UTC option, when I passed UTC:true it started working fine but if I don't pass that param it subtracts one day maybe it's because of timezone. I guess it should be mentioned in docs.

Yes, by default it uses your local time. [UTC option](https://github.com/harrisiirak/cron-parser/blob/master/lib/expression.js#L27-L28) just uses `UTC` as a timezone (you can also achieve the same by passing `tz: 'UTC'` through options) and there aren't currently any other side-effect caused by this. UTC and timezone usage is briefly [documented](https://github.com/harrisiirak/cron-parser#options) under Options section.

**Comment by mohsinamjad** [comment]
@harrisiirak great thanks
