### ISSUE TITLE
Add field setters, ex: setMonth, setMinute, setSecond, etc?

### ISSUE THREAD

**Issue by KevinNovak** [harrisiirak/cron-parser#290]
My application takes in a Cron expression from the user, and I want to adjust this schedule to set the seconds to 0.

It would be cool if cron-parser included a feature to manipulate the various schedule fields (rather than having to extract fields and re-parse), something like the following:

```javascript
let interval = parser.parseExpression(userInput);
interval.setSecond(0)
```

I can workaround this by pulling out fields (`interval.fields.minute`, etc) and then recreating a new expression, however I think field setters like this would be a nice addition.

**Comment by harrisiirak** [comment]
Hi @KevinNovak!

> I can workaround this by pulling out fields (interval.fields.minute, etc) and then recreating a new expression, however I think field setters like this would be a nice addition.

Unfortunately this is currently the only way (also undocumented, therefore I can't really recommend it) how to modify/extend existing cron expression. I would avoid directly modifying parsed interval, instead of that, providing separate `CronExpressionBuilder` (or something similar to that) could be leaner and more usable approach.

What I've in my mind as a rough idea:

```javascript
const expression = CronExpressionBuilder.from('*/2 * * * *').set('minutes', 0).set('seconds', [10, 20]).toExpression();
const interval = parser.parseExpression(expression);
```

That said, providing more stable (and documented) interface for modifying the expression, would be definitely a good addition. However, not completely sure if it's should be part of this library or separate one built upon this one.

More examples from stringify tests: https://github.com/harrisiirak/cron-parser/blob/master/test/stringify.js
