### ISSUE TITLE
Seconds unsupported?

### ISSUE THREAD

**Issue by backspace** [harrisiirak/cron-parser#33]
Hello, thanks for this library, very useful.

The documentation mentions that seconds are optional, but when I specify them, it appears to have no effect. For example:

    parser = require('cron-parser');
    interval = parser.parseExpression('* * * * * *');
    interval.next(); // => Wed Feb 04 2015 16:06:00 GMT-0500 (EST)
    interval.next(); // => Wed Feb 04 2015 16:07:00 GMT-0500 (EST)
    interval.next(); // => Wed Feb 04 2015 16:08:00 GMT-0500 (EST)

Similarly with an every-n-seconds expression:

    interval = parser.parseExpression('*/30 * * * * *');
    interval.next(); // => Wed Feb 04 2015 16:08:00 GMT-0500 (EST)
    interval.next(); // => Wed Feb 04 2015 16:09:00 GMT-0500 (EST)

My use case for this is a bot that reports statistics on the hour by default, but which I can run locally with a ten-second reporting interval so I don’t have to wait for results. I was using an interval in milliseconds before, but it’s desirable to be able to report the statistics on the exact hour mark instead of just once an hour.

Am I doing something incorrectly? I did fork the repository and have a look at fixing it myself but it seemed pretty complicated in there. Maybe it would be simpler for you to reach in directly for the fix, but if not, I could give it another try.

**Comment by harrisiirak** [comment]
Hi! Thank you for reporting that issue. Seems that it broke down after I refactored some code a bit, because it was working in version 0.3. I'll let you know when it's fixed.

Regards,
Harri

**Comment by harrisiirak** [comment]
It should be working as expected. Let me know if you're still experiencing any issue.

**Comment by backspace** [comment]
Success, thanks so much!

**Comment by nemanjapetrovic** [comment]
Hi @harrisiirak ,

it seems that this bug is happening again with the latest release.

Here is my log:


Cron time: * * * * * (every minute)
Running time: 2021-01-10 15:24:48.860 
Next run time: Sun Jan 10 2021 15:25:00 GMT+0100 (Central European Standard Time) 

*Next run time has been printed out without any formatting*

Js code I am trying:

```
var lastRun= new Date();
var interval = cronParser.parseExpression('* * * * *', { currentDate: lastRun });
var nextRun = new Date(interval.next().toString());
console.log(lastRun);
console.log(nextRun);
```

**Comment by harrisiirak** [comment]
@nemanjapetrovic initial report (and fix afterwards) was about seconds not being incremented when it's was present in the expresssion (so this part of the expression was completely ignored), in your case you even don't provide pattern for seconds, which means that 0 value will be be used for the matching.

![image](https://user-images.githubusercontent.com/185315/104125992-cb70cd80-5362-11eb-980d-017deadda477.png)

In case you provide seconds field:

![image](https://user-images.githubusercontent.com/185315/104126021-ee9b7d00-5362-11eb-8045-944644034578.png)

Not completely sure about what the issue is, or what is the expected behaviour in your case.

**Comment by nemanjapetrovic** [comment]
@harrisiirak 

Ah I see, I have to provide an additional `*` for seconds. Thanks! 👍

**Comment by nemanjapetrovic** [comment]
@harrisiirak 

One more question, why are seconds of the next run time always set to 0 if I would like to run cron in every 5 minutes?

```
var cronParser = require('cron-parser');

var lastRun= new Date();
var interval = cronParser.parseExpression('*/5 * * * *', { currentDate: '2021-01-10 15:24:48.860' });
var nextRun = new Date(interval.next().toString());

console.log(interval.next().toString());
console.log(interval.next().toString());
console.log(interval.next().toString());
```

As you can see below the next run time seconds are always 0. The correct next run time would be:

```
2021-01-10 15:29:48.860
2021-01-10 15:34:48.860
and so on...
```

Example:
![image](https://user-images.githubusercontent.com/15672932/104126430-cb6dcf00-535c-11eb-8a0b-7a2dfa2dc721.png)
